export const controlConfig = {
    ControlModels: [
        {
            modelName: "CM - Company Harbour",
            modelType: "control",
            missionType: "ControlModel1",
            buttonIcon: "blank.xpl2",
            modelPath: "ControlModel1.xpl2"
        },
        {
            modelName: "CM - AA",
            modelType: "control",
            missionType: "ControlModel2",
            buttonIcon: "blank.xpl2",
            modelPath: "ControlModel2.xpl2"
        },
        {
            modelName: "CM - AMA",
            modelType: "control",
            missionType: "ControlModel3",
            modelPath: "ControlModel3.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "CM - Ambush",
            modelType: "control",
            missionType: "ControlModel4",
            modelPath: "Ambush.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel5",
            modelType: "control",
            missionType: "ControlModel5",
            modelPath: "ControlModel5.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel6",
            modelType: "control",
            missionType: "ControlModel6",
            modelPath: "ControlModel6.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel7",
            modelType: "control",
            missionType: "ControlModel7",
            modelPath: "ControlModel7.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel8",
            modelType: "control",
            missionType: "ControlModel8",
            modelPath: "ControlModel8.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel9",
            modelType: "controlMeasure",
            missionType: "ControlModel9",
            modelPath: "ControlModel9.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel10",
            modelType: "controlMeasure",
            missionType: "ControlModel10",
            modelPath: "ControlModel10.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel11",
            modelType: "controlMeasure",
            missionType: "ControlModel11",
            modelPath: "ControlModel11.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel12",
            modelType: "controlMeasure",
            missionType: "ControlModel12",
            modelPath: "ControlModel12.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel13",
            modelType: "control",
            missionType: "ControlModel13",
            modelPath: "ControlModel13.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel14",
            modelType: "control",
            missionType: "ControlModel14",
            modelPath: "ControlModel14.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel15",
            modelType: "control",
            missionType: "ControlModel15",
            modelPath: "ControlModel15.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel16",
            modelType: "control",
            missionType: "ControlModel16",
            modelPath: "ControlModel16.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel17",
            modelType: "control",
            missionType: "ControlModel17",
            modelPath: "ControlModel17.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel18",
            modelType: "control",
            missionType: "ControlModel18",
            modelPath: "ControlModel18.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel19",
            modelType: "control",
            missionType: "ControlModel19",
            modelPath: "ControlModel19.xpl2",
            buttonIcon: "blank.xpl2",
        },{
            modelName: "ControlModel10",
            modelType: "controlMeasure",
            missionType: "ControlModel10",
            modelPath: "ControlModel10.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel11",
            modelType: "controlMeasure",
            missionType: "ControlModel11",
            modelPath: "ControlModel11.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel12",
            modelType: "controlMeasure",
            missionType: "ControlModel12",
            modelPath: "ControlModel12.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel23",
            modelType: "control",
            missionType: "ControlModel13",
            modelPath: "ControlModel13.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel24",
            modelType: "control",
            missionType: "ControlModel14",
            modelPath: "ControlModel14.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel25",
            modelType: "control",
            missionType: "ControlModel15",
            modelPath: "ControlModel15.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel26",
            modelType: "control",
            missionType: "ControlModel16",
            modelPath: "ControlModel16.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel27",
            modelType: "control",
            missionType: "ControlModel17",
            modelPath: "ControlModel17.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel28",
            modelType: "control",
            missionType: "ControlModel18",
            modelPath: "ControlModel18.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel29",
            modelType: "control",
            missionType: "ControlModel29",
            modelPath: "ControlModel19.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel11",
            modelType: "controlMeasure",
            missionType: "ControlModel11",
            modelPath: "ControlModel11.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel12",
            modelType: "controlMeasure",
            missionType: "ControlModel12",
            modelPath: "ControlModel12.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel23",
            modelType: "control",
            missionType: "ControlModel13",
            modelPath: "ControlModel13.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel24",
            modelType: "control",
            missionType: "ControlModel14",
            modelPath: "ControlModel14.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel25",
            modelType: "control",
            missionType: "ControlModel15",
            modelPath: "ControlModel15.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel26",
            modelType: "control",
            missionType: "ControlModel16",
            modelPath: "ControlModel16.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel27",
            modelType: "control",
            missionType: "ControlModel17",
            modelPath: "ControlModel17.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel28",
            modelType: "control",
            missionType: "ControlModel18",
            modelPath: "ControlModel18.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel29",
            modelType: "control",
            missionType: "ControlModel29",
            modelPath: "ControlModel19.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel11",
            modelType: "controlMeasure",
            missionType: "ControlModel11",
            modelPath: "ControlModel11.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel12",
            modelType: "controlMeasure",
            missionType: "ControlModel12",
            modelPath: "ControlModel12.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel23",
            modelType: "control",
            missionType: "ControlModel13",
            modelPath: "ControlModel13.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel24",
            modelType: "control",
            missionType: "ControlModel14",
            modelPath: "ControlModel14.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel25",
            modelType: "control",
            missionType: "ControlModel15",
            modelPath: "ControlModel15.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel26",
            modelType: "control",
            missionType: "ControlModel16",
            modelPath: "ControlModel16.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel27",
            modelType: "control",
            missionType: "ControlModel17",
            modelPath: "ControlModel17.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel28",
            modelType: "control",
            missionType: "ControlModel18",
            modelPath: "ControlModel18.xpl2",
            buttonIcon: "blank.xpl2",
        },
        {
            modelName: "ControlModel29",
            modelType: "control",
            missionType: "ControlModel29",
            modelPath: "ControlModel19.xpl2",
            buttonIcon: "blank.xpl2",
        },
    ]
}